import React from "react";
import Frame from "../components/frame";
// import { Container, Card, Row, Col } from 'react-bootstrap'
const AdherentPage = () => {
  return (
    <Frame>
      <div className="table-responsive">
        <table className="table table-hover">
          <thead>
            <tr>
            <th>Nombre</th>
              <th>Nom</th>
              <th>Prénom</th>
              <th>Adhérent</th>
              <th>Téléphone</th>
              <th>email</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <td>1</td>
              <td>RAKOTOMANGA</td>
              <td>Patrick</td>
              <td>Président</td>
              <td>06.66.69.37.50</td>
              <td>rakotozafy.eric@yahoo.fr</td>
            </tr><tr>
            <td>2</td>
              <td>RAMIARISOA</td>
              <td>Roberthine</td>
              <td>Membre</td>
              <td>06.95.27.67.27</td>
              <td>madasoa@gmail.com</td>
            </tr>
         
            <tr>
            <td>3</td>
              <td>RANDRIAMBOLOLONTSOA</td>
              <td>Andriatsimaniry</td>
              <td>Vice-Président</td>
              <td>06.69.68.45.37</td>
              <td>niryomega@free.fr</td>
            </tr>
            <tr>
            <td>4</td>
              <td>RANDRIAMBOLOLONTSOA</td>
              <td>Noro</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>5</td>
              <td>RAMANGASON</td>
              <td>Nirina</td>
              <td>Secrétaire</td>
              <td>06.28.06.03.13</td>
              <td>nramangason@yahoo.com</td>
            </tr>
            <tr>
            <td>6</td>
              <td>PAILLERON</td>
              <td>Christophe</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>7</td>
              <td>REMACLY</td>
              <td>Nathalie</td>
              <td>Secrétaire adjointe</td>
              <td>07.69.33.00.65</td>
              <td>nathalie.remacly@yahoo.fr</td>
            </tr>
            <tr>
            <td>8</td>
              <td>MAURICE</td>
              <td>Joro Rojo</td>
              <td>Trésorière</td>
              <td>06.13.03.25.36</td>
              <td>rojo.jessica@ymail.com</td>
            </tr>
            <tr>
            <td>9</td>
              <td>RAHAERISOA</td>
              <td>Odette</td>
              <td>Trésorière adjointe</td>
              <td>06.79.83.61.58</td>
              <td>odette.rahari@hotmail.fr</td>
            </tr>
            <tr>
            <td>10</td>
              <td>RAHAERISOA</td>
              <td>Joe</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>11</td>
              <td>RAKOTOZANANY</td>
              <td>Alain ADolphe</td>
              <td>Membre</td>
              <td>07.83.12.60.45</td>
              <td>adolpherakotozanany4@gmail.com</td>
            </tr>
            <tr>
            <td>12</td>
              <td>RAKOTOZANANY</td>
              <td>Holy</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>13</td>
              <td>ANDRY</td>
              <td> Luc </td>
              <td>Conseiller</td>
              <td>06.21.32.57.72</td>
              <td>zo_andri@yahoo.com</td>
            </tr>
            <tr>
            <td>14</td>
              <td>ANDRY</td>
              <td>Rinah</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>15</td>
              <td>ANDRIANIRIANA</td>
              <td>Marc</td>
              <td>Conseiller</td>
              <td>06.45.48.40.67</td>
              <td>tyx13090@yahoo.fr</td>
            </tr>
            <tr>
            <td>16</td>
              <td>RABARISON</td>
              <td>Hervé</td>
              <td>Conseiller</td>
              <td>06.09.21.44.73</td>
              <td>doug_rabarison@yahoo.fr</td>
            </tr>
            <tr>
            <td>17</td>
              <td>TOTOLO</td>
              <td>Patrice</td>
              <td>Conseiller</td>
              <td>06.56.86.37.86</td>
              <td>patricet158@gmail.com</td>
            </tr>
            <tr>
            <td>18</td>
              <td>RADAVIDRA</td>
              <td>Tahinaharifomba</td>
              <td>Conseiller</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>19</td>
              <td>RAOERA</td>
              <td>Liva</td>
              <td>Membre</td>
              <td>06.35.28.25.89</td>
              <td></td>
            </tr>
            <tr>
            <td>20</td>
              <td>RAOERA</td>
              <td>Lova</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            
           
            <tr>
            <td>21</td>
              <td>HOUEIX</td>
              <td>Arlette</td>
              <td>Membre</td>
              <td>06.56.82.13.09</td>
              <td>Arlettehouex77@gmail.com</td>
            </tr>
            <tr>
            <td>22</td>
              <td>ANDRIANASOLOARIJAONA</td>
              <td>Christophe</td>
              <td>Conseiller</td>
              <td>06.41.47.33.50</td>
              <td>crristophe@hotmail.com</td>
            </tr>
            <tr>
            <td>23</td>
              <td>ANDRIAMBOLOLONA</td>
              <td>Hery</td>
              <td>Membre</td>
              <td>06.22.75.63.94</td>
              <td></td>
            </tr>
            <tr>
            <td>24</td>
              <td>ANDRIAMBOLOLONA</td>
              <td>Haingo</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            
            <tr>
            <td>25</td>
              <td></td>
              <td>Hermine</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>26</td>
              <td></td>
              <td>Tiana</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>

            <tr>
            <td>27</td>
              <td></td>
              <td>Nomena</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            
            <tr>
            <td>28</td>
              <td>RATSIVOSON</td>
              <td>Fiononana</td>
              <td>Conseillère</td>
              <td></td>
              <td></td>
            </tr>
                      
            <tr>
            <td>29</td>
              <td>RAKOTOARISON</td>
              <td>Ony</td>
              <td>Membre</td>
              <td>06.86.66.34.00</td>
              <td>arisonmiah@gmail.com</td>
            </tr>
            <tr>
            <td>30</td>
              <td>CAMPO</td>
              <td>Nirina (Niks)</td>
              <td>Conseillère</td>
              <td>06.93.41.02.41</td>
              <td>niks109@yahoo.fr</td>
            </tr>
            <tr>
            <td>31</td>
              <td>TOLOJANAHARY</td>
              <td>Aiky</td>
              <td>Membre</td>
              <td>07.89.37.42.99</td>
              <td></td>
            </tr>
            <tr>
            <td>32</td>
              <td>UBACH</td>
              <td> Haingotiana Malala </td>
              <td>Conseillère</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>33</td>
              <td></td>
              <td> Amélie</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>34</td>
              <td></td>
              <td> Sabine </td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>35</td>
              <td></td>
              <td> Nicole </td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>36</td>
              <td>RAKOTOZAFY</td>
              <td> Nandrasana </td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>37</td>
              <td>RAKOTOZAFY</td>
              <td> Hanitra </td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
            <td>38</td>
              <td></td>
              <td>Sabrina</td>
              <td>Membre</td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </Frame>
  );
};

export default AdherentPage;
